# Currently maintained Python versions (as of 2025-11) https://devguide.python.org/versions/
.variables:
  &python_versions
  - "3.10"
  - "3.11"
  - "3.12"
  - "3.13"
  - "3.14"

variables:
  # Python version for build/publish
  LATEST_PYTHON: "3.14"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

default:
  image: python:${PYTHON_VERSION}-slim
  cache:
    paths:
      - .pip-cache/
  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install build twine

stages:
  - build
  - test
  - publish

build:
  image: python:${LATEST_PYTHON}-slim
  stage: build
  variables:
    GIT_DEPTH: 0
  script:
    - apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*
    - python -m build
  artifacts:
    paths:
      - dist/


.test_job_template: &test_job_template
  stage: test
  before_script:
    - python --version
    - pip install dist/*.whl battery_optimizer[dev,hplib]
  parallel:
    matrix:
      - PYTHON_VERSION: *python_versions

.run-tests: &run-tests
  - PYTHONPATH=src pytest --cov-report term-missing --cov=src tests/

glpk:
  <<: *test_job_template
  variables:
    SOLVER: glpk
  script:
    - apt-get update && apt-get install -y --no-install-recommends gcc g++ glpk-utils libglpk-dev && rm -rf /var/lib/apt/lists/*
    - *run-tests

scip:
  <<: *test_job_template
  variables:
    SOLVER: scip
    SCIP_VERSION: 9.2.3
    SHASUM: b95fbd2033276ffe6067f9b2e567e27d1a404f36657bb7a0056242de9630ed64
  script:
    - apt-get update && apt-get install -y --no-install-recommends curl
    - curl https://scipopt.org/download/release/SCIPOptSuite-$SCIP_VERSION-Linux-ubuntu24.deb -o scipopt.deb
    - echo "$SHASUM  scipopt.deb" | sha256sum --check -
    - apt install -y --no-install-recommends ./scipopt.deb && rm -rf /var/lib/apt/lists/*
    - *run-tests

gurobi:
  <<: *test_job_template
  variables:
    SOLVER: gurobi
  script:
    - apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - export GRB_LICENSE_FILE=.secure_files/gurobi.lic
    - pip install dist/*.whl battery_optimizer[gurobi]
    - *run-tests

gurobi-prerelease:
  <<: *test_job_template
  allow_failure: true
  variables:
    SOLVER: gurobi
  script:
    - apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - export GRB_LICENSE_FILE=.secure_files/gurobi.lic
    - pip install --pre gurobipy
    # Install prerelease versions without upper version limits
    - pip install --pre --upgrade --upgrade-strategy eager -r <(sed 's/,<[^[:space:]]*//g' requirements.txt)
    - pip install --no-deps dist/*.whl
    - PYTHONPATH=src pytest -W --cov-report term-missing --cov=src tests/


publish:
  image: python:${LATEST_PYTHON}-slim
  stage: publish
  only:
    - tags
    - master
    - main
  script:
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*