[build-system]
requires = ["setuptools>=70", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_file = "src/battery_optimizer/_version.py"

[project]
name = "battery_optimizer"
dynamic = ["version"]
authors = [
  { name="Carl Hauschke", email="hauschke@fzi.de" },
    { name="Tobias Riedel", email="riedel@fzi.de" },
]
dependencies = [
  "numpy",
  "pandas",
  "matplotlib",
  "pydantic >=2, !=2.12.0",
  "pyomo",
]
description = "Generic Battery Optimizer"
readme = "README.md"
requires-python = ">=3.10"
classifiers=[
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
]

[project.optional-dependencies]
dev = ["pytest", "pyyaml", "pytest-cov", "pytest-watch"]
excel = ["xlsxwriter"]
gurobi = [
  "gurobipy >=11;python_version <= '3.12'",
  "gurobipy >=12;python_version == '3.13'",
  "gurobipy >=13;python_version >= '3.14'",
]
hplib = ["hplib"]

[tool.numpydoc_validation]
checks = [
    "all",   # report on all checks, except the below
    # Optional section
    "SA01",  # See Also
    "EX01",  # Examples
]
